### ISSUE TITLE
currentRequestIndex how this changes when we update the title in firestore.

### ISSUE THREAD

**Issue by deeprajsinghsisodiya** [ParrottKim/riverpod_firestore_realtime_pagination#1]

**Comment by parrottkim** [comment]
currentRequestIndex is working like cursor.

When you update the firestore, only the syntax in 'listen' is executed. 
`var pageExists = currentRequestIndex < _comments.length;`
That means, this syntax return true when you update firestore.

`var currentRequestIndex = _comments.length;`
Because, this syntax is outside of 'listen', so it contains value before you updated.

Please understand that I am not good at English.

**Comment by deeprajsinghsisodiya** [comment]
Thank you very much. You have explained it very well. More power to you. have a good day!
